# Generated by Django 4.1.2 on 2022-12-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_rename_varieties_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='image',
            field=models.ImageField(default='./media/photo/drinks/pngegg', upload_to='photo/varts/'),
            preserve_default=False,
        ),
    ]
